spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3307/shopdb
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    replica:
      jdbc-url: jdbc:mysql://localhost:3308/shopdb
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true